import React from 'react';
import { Link as RouterLink } from 'react-router-dom';
import {
  Box,
  Container,
  Typography,
  Paper,
  Divider,
  Button,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
} from '@mui/material';
import {
  ArrowBack as ArrowBackIcon,
  CheckCircle as CheckCircleIcon,
  ExpandMore as ExpandMoreIcon,
  Gavel as GavelIcon,
  Security as SecurityIcon,
  Block as BlockIcon,
  Payment as PaymentIcon,
  Description as DescriptionIcon,
  Warning as WarningIcon,
} from '@mui/icons-material';

export default function TermsOfService() {
  const lastUpdated = 'December 2, 2025';
  const effectiveDate = 'December 2, 2025';

  return (
    <Box
      sx={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
        py: 4,
      }}
    >
      <Container maxWidth="lg">
        <Button
          component={RouterLink}
          to="/login"
          startIcon={<ArrowBackIcon />}
          sx={{ mb: 3 }}
        >
          Back to Login
        </Button>

        <Paper sx={{ p: 4, borderRadius: 3 }}>
          {/* Header */}
          <Box sx={{ textAlign: 'center', mb: 4 }}>
            <Typography
              variant="h3"
              sx={{
                fontWeight: 700,
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                mb: 2,
              }}
            >
              Terms of Service
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Last Updated: {lastUpdated} | Effective Date: {effectiveDate}
            </Typography>
          </Box>

          <Divider sx={{ mb: 4 }} />

          {/* Important Notice */}
          <Alert severity="info" sx={{ mb: 4 }}>
            <Typography variant="body2">
              <strong>IMPORTANT:</strong> Please read these Terms of Service carefully before using NexPro. By accessing or using our service, you agree to be bound by these terms. If you do not agree, please do not use our service.
            </Typography>
          </Alert>

          {/* Introduction */}
          <Typography variant="body1" paragraph>
            These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "you", or "your") and NexPro ("Company", "we", "us", or "our") governing your use of the NexPro professional office management platform ("Service").
          </Typography>

          <Typography variant="body1" paragraph>
            These Terms are governed by and construed in accordance with the laws of India, including the <strong>Information Technology Act, 2000</strong>, <strong>Indian Contract Act, 1872</strong>, and <strong>Digital Personal Data Protection Act, 2023</strong>.
          </Typography>

          {/* Section 1 - Definitions */}
          <Accordion defaultExpanded>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <DescriptionIcon color="primary" />
                <Typography variant="h6">1. Definitions</Typography>
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <List>
                {[
                  { term: '"Account"', definition: 'means the user account created to access the Service' },
                  { term: '"Organization"', definition: 'means the legal entity (firm, company) subscribing to the Service' },
                  { term: '"User Data"', definition: 'means any data uploaded, entered, or generated by users within the Service' },
                  { term: '"Personal Data"', definition: 'means data as defined under the DPDP Act 2023' },
                  { term: '"Service"', definition: 'means the NexPro platform and all related services' },
                  { term: '"Subscription"', definition: 'means the paid plan selected by the Organization' },
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemText
                      primary={<strong>{item.term}</strong>}
                      secondary={item.definition}
                    />
                  </ListItem>
                ))}
              </List>
            </AccordionDetails>
          </Accordion>

          {/* Section 2 - Account Registration */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <SecurityIcon color="primary" />
                <Typography variant="h6">2. Account Registration and Security</Typography>
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                2.1 Eligibility
              </Typography>
              <Typography paragraph>
                To use NexPro, you must:
              </Typography>
              <List>
                {[
                  'Be at least 18 years of age',
                  'Have the legal capacity to enter into binding contracts',
                  'Be authorized to represent your Organization (for Organization accounts)',
                  'Provide accurate and complete registration information',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="primary" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                2.2 Account Security
              </Typography>
              <Typography paragraph>
                You are responsible for:
              </Typography>
              <List>
                {[
                  'Maintaining the confidentiality of your login credentials',
                  'All activities that occur under your account',
                  'Immediately notifying us of any unauthorized access',
                  'Using strong passwords and enabling two-factor authentication',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="warning" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                2.3 Email Verification
              </Typography>
              <Typography paragraph>
                Account activation requires email verification through OTP (One-Time Password) to ensure authentic user registration as per IT Act requirements.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 3 - Acceptable Use */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <GavelIcon color="primary" />
                <Typography variant="h6">3. Acceptable Use Policy</Typography>
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                3.1 Permitted Use
              </Typography>
              <Typography paragraph>
                You may use NexPro for:
              </Typography>
              <List>
                {[
                  'Managing professional office operations',
                  'Client management and communication',
                  'Task tracking and workflow management',
                  'Document storage and organization',
                  'Generating reports and analytics',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="success" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                3.2 Prohibited Activities
              </Typography>
              <Typography paragraph>
                You shall NOT:
              </Typography>
              <List>
                {[
                  'Use the Service for any unlawful purpose',
                  'Violate any applicable laws including IT Act 2000',
                  'Upload malicious code, viruses, or harmful content',
                  'Attempt to gain unauthorized access to any systems',
                  'Interfere with or disrupt the Service integrity',
                  'Reverse engineer or decompile the software',
                  'Share account credentials with unauthorized persons',
                  'Use the Service to send spam or unsolicited communications',
                  'Store or process illegal content',
                  'Impersonate any person or entity',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><BlockIcon color="error" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>
            </AccordionDetails>
          </Accordion>

          {/* Section 4 - Subscription and Payment */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <PaymentIcon color="primary" />
                <Typography variant="h6">4. Subscription and Payment Terms</Typography>
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                4.1 Free Trial
              </Typography>
              <Typography paragraph>
                New Organizations receive a 30-day free trial with full access to features based on their selected plan tier.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                4.2 Subscription Plans
              </Typography>
              <Typography paragraph>
                We offer the following plans:
              </Typography>
              <List>
                {[
                  'FREE: Basic features with limited users and clients',
                  'STARTER: Enhanced features for small teams',
                  'PROFESSIONAL: Full features for growing practices',
                  'ENTERPRISE: Custom solutions with dedicated support',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="primary" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                4.3 Billing
              </Typography>
              <List>
                {[
                  'Subscriptions are billed monthly or annually in advance',
                  'Prices are exclusive of applicable taxes (GST)',
                  'Payment is due on the subscription renewal date',
                  'Failure to pay may result in service suspension',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="warning" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                4.4 Refund Policy
              </Typography>
              <Typography paragraph>
                Refunds are provided at our discretion. Please contact support for refund requests within 7 days of payment.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 5 - Data Ownership */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">5. Data Ownership and Intellectual Property</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                5.1 Your Data
              </Typography>
              <Typography paragraph>
                You retain all ownership rights to your User Data. By using the Service, you grant us a limited license to process your data solely for providing the Service.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                5.2 Our Intellectual Property
              </Typography>
              <Typography paragraph>
                NexPro, including its design, features, code, and content, is owned by us and protected by intellectual property laws. You may not copy, modify, or create derivative works without permission.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                5.3 Feedback
              </Typography>
              <Typography paragraph>
                Any feedback, suggestions, or improvements you provide may be used by us without any obligation to you.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 6 - Privacy and Data Protection */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">6. Privacy and Data Protection</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography paragraph>
                Your privacy is important to us. Please refer to our{' '}
                <RouterLink to="/privacy-policy" style={{ color: '#667eea' }}>
                  Privacy Policy
                </RouterLink>{' '}
                for details on how we collect, use, and protect your personal data in compliance with the DPDP Act 2023.
              </Typography>
              <Typography paragraph>
                Key commitments:
              </Typography>
              <List>
                {[
                  'Data processed only for legitimate purposes',
                  'Reasonable security measures implemented',
                  'Your rights as Data Principal respected',
                  'Data breach notification as required by law',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="primary" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>
            </AccordionDetails>
          </Accordion>

          {/* Section 7 - Disclaimer and Limitation of Liability */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <WarningIcon color="warning" />
                <Typography variant="h6">7. Disclaimer and Limitation of Liability</Typography>
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                7.1 Service Disclaimer
              </Typography>
              <Typography paragraph>
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT GUARANTEE UNINTERRUPTED OR ERROR-FREE SERVICE.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                7.2 Limitation of Liability
              </Typography>
              <Typography paragraph>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW:
              </Typography>
              <List>
                {[
                  'We shall not be liable for indirect, incidental, or consequential damages',
                  'Our total liability shall not exceed the subscription fees paid in the preceding 12 months',
                  'We are not liable for damages arising from third-party actions or force majeure events',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><WarningIcon color="warning" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                7.3 Professional Advice Disclaimer
              </Typography>
              <Typography paragraph>
                NexPro is a management tool and does not provide legal, tax, or professional advice. Users should consult qualified professionals for such matters.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 8 - Termination */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">8. Termination</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                8.1 Termination by You
              </Typography>
              <Typography paragraph>
                You may terminate your account at any time through the account settings. Upon termination, you will have 30 days to export your data.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                8.2 Termination by Us
              </Typography>
              <Typography paragraph>
                We may suspend or terminate your account if:
              </Typography>
              <List>
                {[
                  'You violate these Terms of Service',
                  'You fail to pay subscription fees',
                  'Required by law or court order',
                  'The Service is discontinued',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><BlockIcon color="error" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>

              <Typography variant="subtitle1" gutterBottom fontWeight={600} sx={{ mt: 2 }}>
                8.3 Effect of Termination
              </Typography>
              <Typography paragraph>
                Upon termination, your access to the Service will be revoked. Your data will be retained for 30 days to allow export, after which it will be deleted (except as required for legal compliance).
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 9 - Dispute Resolution */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">9. Dispute Resolution</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                9.1 Governing Law
              </Typography>
              <Typography paragraph>
                These Terms shall be governed by and construed in accordance with the laws of India.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                9.2 Arbitration
              </Typography>
              <Typography paragraph>
                Any dispute arising out of these Terms shall be resolved through arbitration under the Arbitration and Conciliation Act, 1996. The arbitration shall be conducted in English, and the seat of arbitration shall be Mumbai, India.
              </Typography>

              <Typography variant="subtitle1" gutterBottom fontWeight={600}>
                9.3 Jurisdiction
              </Typography>
              <Typography paragraph>
                Subject to arbitration provisions, courts in Mumbai, India shall have exclusive jurisdiction.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 10 - Modifications */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">10. Modifications to Terms</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography paragraph>
                We reserve the right to modify these Terms at any time. Material changes will be communicated through:
              </Typography>
              <List>
                {[
                  'Email notification to registered users',
                  'Prominent notice on the application',
                  'Updated "Last Updated" date',
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemIcon><CheckCircleIcon color="primary" /></ListItemIcon>
                    <ListItemText primary={item} />
                  </ListItem>
                ))}
              </List>
              <Typography paragraph>
                Continued use after modifications constitutes acceptance of the new Terms.
              </Typography>
            </AccordionDetails>
          </Accordion>

          {/* Section 11 - Miscellaneous */}
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">11. Miscellaneous</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <List>
                {[
                  { primary: 'Entire Agreement', secondary: 'These Terms, along with Privacy Policy, constitute the entire agreement between you and us.' },
                  { primary: 'Severability', secondary: 'If any provision is found invalid, the remaining provisions remain in effect.' },
                  { primary: 'Waiver', secondary: 'Failure to enforce any right does not constitute a waiver of that right.' },
                  { primary: 'Assignment', secondary: 'You may not assign these Terms without our consent. We may assign to affiliates or successors.' },
                  { primary: 'Force Majeure', secondary: 'We are not liable for delays due to circumstances beyond our reasonable control.' },
                ].map((item, index) => (
                  <ListItem key={index}>
                    <ListItemText
                      primary={<strong>{item.primary}</strong>}
                      secondary={item.secondary}
                    />
                  </ListItem>
                ))}
              </List>
            </AccordionDetails>
          </Accordion>

          {/* Section 12 - Contact */}
          <Accordion defaultExpanded>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography variant="h6">12. Contact Information</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography paragraph>
                For questions or concerns about these Terms, please contact us:
              </Typography>
              <Paper variant="outlined" sx={{ p: 3, bgcolor: 'primary.50' }}>
                <Typography variant="body1">
                  <strong>NexPro</strong><br />
                  Email: chinmaytechsoft@gmail.com<br />
                  Grievance Officer: chinmaytechsoft@gmail.com<br />
                  Response Time: Within 48 hours for urgent matters
                </Typography>
              </Paper>
            </AccordionDetails>
          </Accordion>

          <Divider sx={{ my: 4 }} />

          {/* Acceptance */}
          <Alert severity="success" sx={{ mb: 2 }}>
            <Typography variant="body2">
              By clicking "Sign Up" or "I Accept" or by using NexPro, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </Typography>
          </Alert>

          {/* Footer */}
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant="body2" color="text.secondary">
              These Terms are compliant with:
            </Typography>
            <Typography variant="body2" color="primary" sx={{ fontWeight: 600 }}>
              Information Technology Act, 2000 | Indian Contract Act, 1872 | DPDP Act, 2023
            </Typography>
          </Box>
        </Paper>
      </Container>
    </Box>
  );
}
