# Generated by Django 5.0.1 on 2025-11-17 04:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(max_length=50, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                ("PAN", models.CharField(blank=True, max_length=10, null=True)),
                ("GSTIN", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("FIRM", "Firm"),
                            ("COMPANY", "Company"),
                            ("TRUST", "Trust"),
                            ("HUF", "HUF"),
                            ("OTHERS", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients",
                "ordering": ["client_name"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=255)),
                ("subject_template", models.CharField(max_length=500)),
                (
                    "body_template",
                    models.TextField(
                        help_text="HTML/Text template with placeholders: {{client_name}}, {{PAN}}, {{GSTIN}}, {{period_label}}, {{due_date}}, {{work_name}}, {{firm_name}}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["work_type", "template_name"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_name", models.CharField(max_length=255)),
                (
                    "statutory_form",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "default_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("ONE_TIME", "One-time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "work_types",
                "ordering": ["work_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("PARTNER", "Partner"),
                            ("MANAGER", "Manager"),
                            ("STAFF", "Staff"),
                        ],
                        default="STAFF",
                        max_length=20,
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientWorkMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "freq_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("ONE_TIME", "One-time"),
                        ],
                        help_text="Optional frequency override. If not set, uses WorkType's default frequency",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "start_from_period",
                    models.CharField(
                        help_text="E.g., 'FY 2024-25', 'Apr 2025', 'Q1 2025-26'",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_mappings",
                        to="core.client",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_mappings",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "db_table": "client_work_mappings",
                "ordering": ["client", "work_type"],
            },
        ),
        migrations.CreateModel(
            name="CredentialVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portal_type",
                    models.CharField(
                        choices=[
                            ("GST", "GST Portal"),
                            ("INCOME_TAX", "Income Tax Portal"),
                            ("TDS", "TDS Portal"),
                            ("MCA", "MCA Portal"),
                            ("BANK", "Bank Portal"),
                            ("OTHERS", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("login_url", models.URLField(blank=True, max_length=500, null=True)),
                ("username", models.CharField(max_length=255)),
                (
                    "password_enc",
                    models.TextField(help_text="Encrypted password using Fernet"),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, help_text="Security Q&A, notes, etc.", null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "db_table": "credential_vault",
                "ordering": ["client", "portal_type"],
            },
        ),
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_days",
                    models.IntegerField(
                        help_text="Days relative to due_date (negative for before, positive for after). E.g., -7 means 7 days before due date"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_REMINDER", "Document Reminder"),
                            ("FILING_REMINDER", "Filing Reminder"),
                            ("OVERDUE_REMINDER", "Overdue Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("repeat_if_pending", models.BooleanField(default=False)),
                (
                    "repeat_interval",
                    models.IntegerField(default=3, help_text="Days between repeats"),
                ),
                (
                    "max_repeats",
                    models.IntegerField(
                        default=3, help_text="Maximum number of times to repeat"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_rules",
                        to="core.emailtemplate",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_rules",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_rules",
                "ordering": ["work_type", "offset_days"],
            },
        ),
        migrations.CreateModel(
            name="WorkInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        help_text="E.g., 'Apr 2025', 'Q1 2025-26', 'FY 2025-26'",
                        max_length=100,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("STARTED", "Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.clientworkmapping",
                    ),
                ),
            ],
            options={
                "db_table": "work_instances",
                "ordering": ["due_date", "client_work"],
            },
        ),
        migrations.CreateModel(
            name="ReminderInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("repeat_count", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("email_to", models.EmailField(max_length=254)),
                (
                    "subject_rendered",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("body_rendered", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reminder_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.reminderrule",
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_instances",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="work_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="core.worktype",
            ),
        ),
        migrations.AddIndex(
            model_name="workinstance",
            index=models.Index(
                fields=["status", "due_date"], name="work_instan_status_a72c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workinstance",
            index=models.Index(
                fields=["assigned_to", "status"], name="work_instan_assigne_81c414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderinstance",
            index=models.Index(
                fields=["send_status", "scheduled_at"],
                name="reminder_in_send_st_890a25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderinstance",
            index=models.Index(
                fields=["work_instance", "send_status"],
                name="reminder_in_work_in_d6f897_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientworkmapping",
            unique_together={("client", "work_type")},
        ),
    ]
