# Generated by Django 5.0.1 on 2025-11-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="For Individual/HUF", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_incorporation",
            field=models.DateField(
                blank=True, help_text="For Firm/Company/Trust", null=True
            ),
        ),
    ]
