# Generated by Django 5.0.1 on 2025-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_client_date_of_birth_client_date_of_incorporation"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="group",
            field=models.CharField(
                blank=True, help_text="Client group name", max_length=100, null=True
            ),
        ),
    ]
