# Generated by Django 5.0.1 on 2025-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_client_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="enable_reminders",
            field=models.BooleanField(
                default=True, help_text="Enable automatic reminders for this work type"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="reminder_frequency_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("ALTERNATE_DAYS", "Every Alternate Days"),
                    ("WEEKLY", "Weekly (Specific Days)"),
                    ("CUSTOM", "Custom Interval"),
                ],
                default="ALTERNATE_DAYS",
                help_text="How frequently to send reminders",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="reminder_interval_days",
            field=models.IntegerField(
                default=2,
                help_text="For ALTERNATE_DAYS: 2, for CUSTOM: specify custom interval",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="reminder_start_day",
            field=models.IntegerField(
                default=1,
                help_text="Day of month/period to start sending reminders (e.g., 1 for 1st of month)",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="reminder_weekdays",
            field=models.CharField(
                blank=True,
                help_text="For WEEKLY: comma-separated weekday numbers (0=Monday, 6=Sunday). E.g., '0' for Monday, '0,2,4' for Mon/Wed/Fri",
                max_length=50,
                null=True,
            ),
        ),
    ]
