# Generated by Django 5.0.1 on 2025-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_worktype_enable_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialvault",
            name="portal_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Portal name (e.g., GST Portal, Income Tax Portal, etc.)",
                max_length=255,
            ),
        ),
    ]
