# Generated by Django 5.0.1 on 2025-11-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_credentialvault_portal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="due_date_day",
            field=models.IntegerField(
                default=20, help_text="Day of month when task is due (1-31)"
            ),
        ),
    ]
