# Generated by Django 5.0.1 on 2025-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_worktype_due_date_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_credential_types",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated portal types staff can access (e.g., 'GST,INCOME_TAX,TDS'). Empty means no access.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Allow this staff member to access credential vault",
            ),
        ),
    ]
