# Generated by Django 5.0.1 on 2025-11-28 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_allowed_credential_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization/Firm name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        blank=True,
                        help_text="Subdomain for tenant (e.g., 'firmname' for firmname.nexpro.com)",
                        max_length=63,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Trial"),
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_users",
                    models.IntegerField(default=2, help_text="Maximum users allowed"),
                ),
                (
                    "max_clients",
                    models.IntegerField(
                        default=10, help_text="Maximum clients allowed"
                    ),
                ),
                (
                    "firm_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for documents/emails",
                        max_length=255,
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Default sender email for this organization",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "encryption_key",
                    models.CharField(
                        blank=True,
                        help_text="Tenant-specific Fernet encryption key",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Trial"),
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("PAUSED", "Paused"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(
                default=False,
                help_text="Platform administrator - can manage all organizations",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="clientworkmapping",
            name="freq_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                    ("ONE_TIME", "One-time"),
                ],
                help_text="Optional frequency override",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reminderrule",
            name="offset_days",
            field=models.IntegerField(
                help_text="Days relative to due_date (negative for before, positive for after)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="allowed_credential_types",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated portal types staff can access",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="reminder_start_day",
            field=models.IntegerField(
                default=1, help_text="Day of month/period to start sending reminders"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="reminder_weekdays",
            field=models.CharField(
                blank=True,
                help_text="For WEEKLY: comma-separated weekday numbers (0=Monday, 6=Sunday)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="clientworkmapping",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="credentialvault",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="reminderinstance",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="workinstance",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("organization", "client_code")},
        ),
        migrations.AddIndex(
            model_name="reminderinstance",
            index=models.Index(
                fields=["organization", "send_status"],
                name="reminder_in_organiz_3dab35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workinstance",
            index=models.Index(
                fields=["organization", "status"], name="work_instan_organiz_6c688d_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="core.organization",
            ),
        ),
    ]
