# Generated by Django 5.0.1 on 2025-11-28 10:58

from django.db import migrations
import uuid


def migrate_to_multi_tenant(apps, schema_editor):
    """
    Migrate existing data to a default organization.
    Creates a default organization and assigns all existing data to it.
    """
    Organization = apps.get_model('core', 'Organization')
    User = apps.get_model('core', 'User')
    Client = apps.get_model('core', 'Client')
    WorkType = apps.get_model('core', 'WorkType')
    ClientWorkMapping = apps.get_model('core', 'ClientWorkMapping')
    WorkInstance = apps.get_model('core', 'WorkInstance')
    EmailTemplate = apps.get_model('core', 'EmailTemplate')
    ReminderRule = apps.get_model('core', 'ReminderRule')
    ReminderInstance = apps.get_model('core', 'ReminderInstance')
    CredentialVault = apps.get_model('core', 'CredentialVault')

    # Check if there's any existing data that needs migration
    has_users = User.objects.filter(organization__isnull=True).exists()
    has_clients = Client.objects.filter(organization__isnull=True).exists()
    has_work_types = WorkType.objects.filter(organization__isnull=True).exists()

    if not (has_users or has_clients or has_work_types):
        # No existing data to migrate
        return

    # Create default organization for existing data
    default_org, created = Organization.objects.get_or_create(
        slug='default',
        defaults={
            'id': uuid.uuid4(),
            'name': 'Default Organization',
            'email': 'admin@default.org',
            'plan': 'PROFESSIONAL',
            'status': 'ACTIVE',
            'max_users': 15,
            'max_clients': 200,
        }
    )

    # Migrate all existing users to default organization
    User.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing clients
    Client.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing work types
    WorkType.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing client-work mappings
    ClientWorkMapping.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing work instances
    WorkInstance.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing email templates
    EmailTemplate.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing reminder rules
    ReminderRule.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing reminder instances
    ReminderInstance.objects.filter(organization__isnull=True).update(organization=default_org)

    # Migrate all existing credential vaults
    CredentialVault.objects.filter(organization__isnull=True).update(organization=default_org)

    # Make the first admin user a platform admin if one exists
    first_admin = User.objects.filter(role='ADMIN', organization=default_org).first()
    if first_admin:
        first_admin.is_platform_admin = True
        first_admin.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - remove organization references.
    This doesn't delete the organization, just nullifies the FKs.
    """
    User = apps.get_model('core', 'User')
    Client = apps.get_model('core', 'Client')
    WorkType = apps.get_model('core', 'WorkType')
    ClientWorkMapping = apps.get_model('core', 'ClientWorkMapping')
    WorkInstance = apps.get_model('core', 'WorkInstance')
    EmailTemplate = apps.get_model('core', 'EmailTemplate')
    ReminderRule = apps.get_model('core', 'ReminderRule')
    ReminderInstance = apps.get_model('core', 'ReminderInstance')
    CredentialVault = apps.get_model('core', 'CredentialVault')

    # Remove organization references
    User.objects.all().update(organization=None, is_platform_admin=False)
    Client.objects.all().update(organization=None)
    WorkType.objects.all().update(organization=None)
    ClientWorkMapping.objects.all().update(organization=None)
    WorkInstance.objects.all().update(organization=None)
    EmailTemplate.objects.all().update(organization=None)
    ReminderRule.objects.all().update(organization=None)
    ReminderInstance.objects.all().update(organization=None)
    CredentialVault.objects.all().update(organization=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_organization_subscription_user_is_platform_admin_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_to_multi_tenant, reverse_migration),
    ]
