# Generated by Django 5.0.1 on 2025-12-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_migrate_to_multi_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderinstance",
            name="recipient_type",
            field=models.CharField(
                choices=[("CLIENT", "Client"), ("EMPLOYEE", "Employee")],
                default="CLIENT",
                help_text="Type of recipient",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("EMPLOYEE", "Employee/Internal"),
                    ("BOTH", "Both Client & Employee"),
                ],
                default="CLIENT",
                help_text="Who should receive this reminder",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="client_reminder_end_day",
            field=models.IntegerField(
                default=0,
                help_text="Day to stop client reminders (0 = due date, -1 = day before due)",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="client_reminder_frequency_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("ALTERNATE_DAYS", "Every Alternate Days"),
                    ("WEEKLY", "Weekly (Specific Days)"),
                    ("CUSTOM", "Custom Interval"),
                ],
                default="ALTERNATE_DAYS",
                help_text="How frequently to send client reminders",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="client_reminder_interval_days",
            field=models.IntegerField(
                default=2, help_text="Days between client reminders"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="client_reminder_start_day",
            field=models.IntegerField(
                default=1,
                help_text="Day of month/period to start sending client reminders",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="client_reminder_weekdays",
            field=models.CharField(
                blank=True,
                help_text="For WEEKLY: comma-separated weekday numbers (0=Mon, 6=Sun)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="employee_reminder_end_day",
            field=models.IntegerField(
                default=0, help_text="Day to stop employee reminders (0 = due date)"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="employee_reminder_frequency_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("ALTERNATE_DAYS", "Every Alternate Days"),
                    ("WEEKLY", "Weekly (Specific Days)"),
                    ("CUSTOM", "Custom Interval"),
                ],
                default="DAILY",
                help_text="How frequently to send employee reminders",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="employee_reminder_interval_days",
            field=models.IntegerField(
                default=1, help_text="Days between employee reminders"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="employee_reminder_start_day",
            field=models.IntegerField(
                default=1,
                help_text="Day of month/period to start sending employee reminders",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="employee_reminder_weekdays",
            field=models.CharField(
                blank=True,
                help_text="For WEEKLY: comma-separated weekday numbers (0=Mon, 6=Sun)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="enable_client_reminders",
            field=models.BooleanField(
                default=True, help_text="Enable automatic reminders to clients"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="enable_employee_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic reminders to assigned employees",
            ),
        ),
        migrations.AlterField(
            model_name="reminderinstance",
            name="reminder_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="core.reminderrule",
            ),
        ),
        migrations.AlterField(
            model_name="reminderinstance",
            name="send_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("SKIPPED", "Skipped - Task Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reminderinstance",
            index=models.Index(
                fields=["recipient_type", "send_status"],
                name="reminder_in_recipie_4004f5_idx",
            ),
        ),
    ]
