# Generated by Django 5.0.1 on 2025-12-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_reminderinstance_recipient_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="employee_notification_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email Only"),
                    ("IN_APP", "In-App Notification Only"),
                    ("BOTH", "Both Email & In-App"),
                ],
                default="BOTH",
                help_text="How to notify employees (email, in-app, or both)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REMINDER", "Task Reminder"),
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("TASK_OVERDUE", "Task Overdue"),
                            ("SYSTEM", "System Notification"),
                        ],
                        default="REMINDER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "reminder_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.reminderinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["organization", "user", "-created_at"],
                        name="notificatio_organiz_75165a_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "is_read"],
                        name="notificatio_notific_72d27e_idx",
                    ),
                ],
            },
        ),
    ]
