# Generated by Django 5.0.1 on 2025-12-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_worktype_employee_notification_type_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="allowed_credential_types",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_access_credentials",
        ),
        migrations.CreateModel(
            name="WorkTypeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_type_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_type_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "db_table": "work_type_assignments",
                "ordering": ["work_type__work_name", "employee__first_name"],
                "unique_together": {("work_type", "employee", "organization")},
            },
        ),
    ]
