# Generated by Django 5.0.1 on 2025-12-01 13:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_work_type_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=core.models.task_document_upload_path),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type", max_length=100, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "task_documents",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["work_instance", "-uploaded_at"],
                        name="task_docume_work_in_2b2f2e_idx",
                    ),
                    models.Index(
                        fields=["organization", "-uploaded_at"],
                        name="task_docume_organiz_7ebe97_idx",
                    ),
                ],
            },
        ),
    ]
