# Generated by Django 5.0.1 on 2025-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_taskdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinstance",
            name="is_timer_running",
            field=models.BooleanField(
                default=False, help_text="Whether the timer is currently running"
            ),
        ),
        migrations.AddField(
            model_name="workinstance",
            name="timer_started_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when timer was last started", null=True
            ),
        ),
        migrations.AddField(
            model_name="workinstance",
            name="total_time_spent",
            field=models.IntegerField(
                default=0,
                help_text="Total time spent in seconds (accumulated across pause/resume cycles)",
            ),
        ),
        migrations.AlterField(
            model_name="workinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("OVERDUE", "Overdue"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
