# Generated by Django 5.0.1 on 2025-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_workinstance_is_timer_running_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["work_type", "template_type", "template_name"]},
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client Reminder"),
                    ("EMPLOYEE", "Employee/Internal Reminder"),
                ],
                default="CLIENT",
                help_text="Type of reminder this template is for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body_template",
            field=models.TextField(
                help_text="HTML/Text template with placeholders: {{client_name}}, {{PAN}}, {{GSTIN}}, {{period_label}}, {{due_date}}, {{work_name}}, {{firm_name}}, {{employee_name}}"
            ),
        ),
    ]
