# Generated by Django 5.0.1 on 2025-12-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_add_template_type_to_email_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Admin Report",
                        help_text="Name for this report configuration",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this report should be sent"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="WEEKLY",
                        help_text="How often to send the report",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        help_text="For weekly reports: which day to send",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        default=1,
                        help_text="For monthly reports: which day to send (1-28)",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        default="09:00:00",
                        help_text="Time of day to send the report (24-hour format)",
                    ),
                ),
                (
                    "recipient_emails",
                    models.TextField(
                        help_text="Comma-separated list of email addresses to receive the report"
                    ),
                ),
                (
                    "include_summary",
                    models.BooleanField(
                        default=True, help_text="Include overall summary statistics"
                    ),
                ),
                (
                    "include_client_wise",
                    models.BooleanField(
                        default=True, help_text="Include client-wise task breakdown"
                    ),
                ),
                (
                    "include_employee_wise",
                    models.BooleanField(
                        default=True, help_text="Include employee-wise task breakdown"
                    ),
                ),
                (
                    "include_work_type_wise",
                    models.BooleanField(
                        default=True, help_text="Include work type-wise task breakdown"
                    ),
                ),
                (
                    "include_status_breakdown",
                    models.BooleanField(
                        default=True,
                        help_text="Include status breakdown (completed, overdue, pending, etc.)",
                    ),
                ),
                (
                    "include_overdue_list",
                    models.BooleanField(
                        default=True, help_text="Include detailed list of overdue tasks"
                    ),
                ),
                (
                    "include_upcoming_dues",
                    models.BooleanField(
                        default=True, help_text="Include list of upcoming due tasks"
                    ),
                ),
                (
                    "include_charts",
                    models.BooleanField(
                        default=True,
                        help_text="Include visual charts and graphs in the report",
                    ),
                ),
                (
                    "report_period",
                    models.CharField(
                        choices=[
                            ("CURRENT_DAY", "Current Day"),
                            ("LAST_7_DAYS", "Last 7 Days"),
                            ("LAST_30_DAYS", "Last 30 Days"),
                            ("CURRENT_MONTH", "Current Month"),
                            ("CURRENT_QUARTER", "Current Quarter"),
                            ("CURRENT_FY", "Current Financial Year"),
                        ],
                        default="LAST_7_DAYS",
                        help_text="Time period for report data",
                        max_length=30,
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was last sent", null=True
                    ),
                ),
                (
                    "last_sent_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of the last send attempt",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "report_configurations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="report_conf_organiz_fd9d38_idx",
                    ),
                    models.Index(
                        fields=["frequency", "is_active"],
                        name="report_conf_frequen_2edfa9_idx",
                    ),
                ],
            },
        ),
    ]
