# Generated by Django 5.0.1 on 2025-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_report_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="auto_start_on_creation",
            field=models.BooleanField(
                default=True,
                help_text="For auto-driven: automatically set status to STARTED when task is created",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="is_auto_driven",
            field=models.BooleanField(
                default=False,
                help_text="Auto-driven tasks start automatically and send reminders until completed. Example: GSR 1 document reminder",
            ),
        ),
    ]
