# Generated by Django 5.0.1 on 2025-12-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_add_auto_driven_work_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar",
            field=models.CharField(
                blank=True, help_text="Aadhar number", max_length=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="joining_date",
            field=models.DateField(blank=True, help_text="Date of joining", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pan",
            field=models.CharField(
                blank=True, help_text="PAN number", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly salary",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address for sending", max_length=254
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name (e.g., 'GST Team', 'ITR Department')",
                        max_length=100,
                    ),
                ),
                (
                    "use_custom_smtp",
                    models.BooleanField(
                        default=False,
                        help_text="Use custom SMTP settings instead of default",
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("smtp_port", models.IntegerField(blank=True, default=587, null=True)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as default email for this organization",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_emails",
                "ordering": ["-is_default", "display_name"],
                "unique_together": {("organization", "email_address")},
            },
        ),
        migrations.AddField(
            model_name="worktype",
            name="sender_email",
            field=models.ForeignKey(
                blank=True,
                help_text="Email account to use for sending reminders for this work type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_types",
                to="core.organizationemail",
            ),
        ),
    ]
