# Generated by Django 5.0.1 on 2025-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_employee_details_and_org_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_email_reminders",
            field=models.BooleanField(
                default=True, help_text="Receive email reminders for due tasks"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_overdue_alerts",
            field=models.BooleanField(
                default=True, help_text="Receive alerts for overdue tasks"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_task_assignments",
            field=models.BooleanField(
                default=True, help_text="Receive notifications for task assignments"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_weekly_reports",
            field=models.BooleanField(
                default=False, help_text="Receive weekly summary reports"
            ),
        ),
    ]
