# Generated by Django 5.0.1 on 2025-12-01 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_add_upgrade_request_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email at time of action (preserved if user deleted)",
                        max_length=254,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("LOGIN_FAILED", "Failed Login Attempt"),
                            ("SIGNUP", "User Registration"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PROFILE_UPDATE", "Profile Updated"),
                            ("DATA_ACCESS", "Data Accessed"),
                            ("DATA_EXPORT", "Data Exported"),
                            ("DATA_DELETE", "Data Deleted"),
                            ("CLIENT_CREATE", "Client Created"),
                            ("CLIENT_UPDATE", "Client Updated"),
                            ("CLIENT_DELETE", "Client Deleted"),
                            ("SETTINGS_CHANGE", "Settings Changed"),
                            ("OTP_SENT", "OTP Sent"),
                            ("OTP_VERIFIED", "OTP Verified"),
                            ("OTP_FAILED", "OTP Verification Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_logs_user_id_6193b2_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_logs_organiz_86ff70_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_logs_ip_addr_919cb4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for OTP verification", max_length=254
                    ),
                ),
                ("otp", models.CharField(help_text="6-digit OTP code", max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SIGNUP", "Email Verification for Signup"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("EMAIL_CHANGE", "Email Change Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=5, help_text="Maximum allowed attempts"
                    ),
                ),
                (
                    "signup_data",
                    models.JSONField(
                        blank=True,
                        help_text="Encrypted signup form data stored until email is verified",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="OTP expiry time")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User requesting password reset",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_verified"],
                        name="email_otps_email_c12e2a_idx",
                    ),
                    models.Index(
                        fields=["otp", "email"], name="email_otps_otp_776124_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="email_otps_expires_040e75_idx"
                    ),
                ],
            },
        ),
    ]
