# Generated by Django 5.0.1 on 2025-12-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_add_otp_and_audit_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="NexPro",
                        help_text="Platform display name",
                        max_length=100,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@nexpro.com",
                        help_text="Support contact email",
                        max_length=254,
                    ),
                ),
                (
                    "enable_signups",
                    models.BooleanField(
                        default=True, help_text="Allow new organization registrations"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode (blocks all non-admin access)",
                    ),
                ),
                (
                    "default_trial_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Default trial period for new organizations",
                    ),
                ),
                (
                    "max_free_users",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum users allowed in free plan"
                    ),
                ),
                (
                    "max_free_clients",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum clients allowed in free plan"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True,
                        help_text="Require email verification for new signups",
                    ),
                ),
                (
                    "allow_password_reset",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to reset passwords via email",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
                "db_table": "platform_settings",
            },
        ),
    ]
