# Generated by Django 5.0.1 on 2025-12-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_platform_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable SMTP email sending"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_from_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Default sender email address",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_from_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default sender display name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SMTP server hostname (e.g., smtp.gmail.com)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SMTP password (stored encrypted)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(
                default=587, help_text="SMTP server port (587 for TLS, 465 for SSL)"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_use_ssl",
            field=models.BooleanField(
                default=False,
                help_text="Use SSL encryption (mutually exclusive with TLS)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, help_text="Use TLS encryption"),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="smtp_username",
            field=models.CharField(
                blank=True, default="", help_text="SMTP username/email", max_length=255
            ),
        ),
    ]
