# Generated by Django 5.0.1 on 2025-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_add_smtp_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique plan identifier (e.g., FREE, STARTER, PROFESSIONAL)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the plan", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Plan description for users"
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly subscription price",
                        max_digits=10,
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yearly subscription price",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR",
                        help_text="Currency code (INR, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum users allowed"
                    ),
                ),
                (
                    "max_clients",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum clients allowed"
                    ),
                ),
                (
                    "max_storage_mb",
                    models.PositiveIntegerField(
                        default=100, help_text="Maximum storage in MB"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features included in this plan",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for subscription",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default plan for new signups"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
    ]
