# Generated by Django 5.0.1 on 2025-12-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_add_subscription_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSyncSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_tasks_to_google",
                    models.BooleanField(
                        default=True, help_text="Sync NexPro tasks to Google Tasks"
                    ),
                ),
                (
                    "sync_google_to_tasks",
                    models.BooleanField(
                        default=True,
                        help_text="Sync Google Tasks changes back to NexPro (two-way sync)",
                    ),
                ),
                (
                    "task_sync_frequency",
                    models.CharField(
                        choices=[
                            ("REALTIME", "Real-time (on task changes)"),
                            ("HOURLY", "Every hour"),
                            ("DAILY", "Once daily"),
                            ("MANUAL", "Manual sync only"),
                        ],
                        default="REALTIME",
                        help_text="How often to sync tasks",
                        max_length=20,
                    ),
                ),
                (
                    "sync_tasks_to_calendar",
                    models.BooleanField(
                        default=True,
                        help_text="Create Google Calendar events for tasks",
                    ),
                ),
                (
                    "sync_calendar_to_tasks",
                    models.BooleanField(
                        default=False,
                        help_text="Sync Calendar event changes back to NexPro",
                    ),
                ),
                (
                    "calendar_sync_frequency",
                    models.CharField(
                        choices=[
                            ("REALTIME", "Real-time (on task changes)"),
                            ("HOURLY", "Every hour"),
                            ("DAILY", "Once daily"),
                            ("MANUAL", "Manual sync only"),
                        ],
                        default="REALTIME",
                        help_text="How often to sync calendar",
                        max_length=20,
                    ),
                ),
                (
                    "calendar_reminder_1",
                    models.IntegerField(
                        choices=[
                            (0, "At due time"),
                            (5, "5 minutes before"),
                            (10, "10 minutes before"),
                            (15, "15 minutes before"),
                            (30, "30 minutes before"),
                            (60, "1 hour before"),
                            (120, "2 hours before"),
                            (1440, "1 day before"),
                            (2880, "2 days before"),
                            (10080, "1 week before"),
                        ],
                        default=1440,
                        help_text="First reminder time (minutes before due)",
                    ),
                ),
                (
                    "calendar_reminder_2",
                    models.IntegerField(
                        choices=[
                            (0, "At due time"),
                            (5, "5 minutes before"),
                            (10, "10 minutes before"),
                            (15, "15 minutes before"),
                            (30, "30 minutes before"),
                            (60, "1 hour before"),
                            (120, "2 hours before"),
                            (1440, "1 day before"),
                            (2880, "2 days before"),
                            (10080, "1 week before"),
                        ],
                        default=60,
                        help_text="Second reminder time (minutes before due)",
                    ),
                ),
                (
                    "calendar_reminder_3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "At due time"),
                            (5, "5 minutes before"),
                            (10, "10 minutes before"),
                            (15, "15 minutes before"),
                            (30, "30 minutes before"),
                            (60, "1 hour before"),
                            (120, "2 hours before"),
                            (1440, "1 day before"),
                            (2880, "2 days before"),
                            (10080, "1 week before"),
                        ],
                        help_text="Third reminder time (optional)",
                        null=True,
                    ),
                ),
                (
                    "reminder_method_popup",
                    models.BooleanField(default=True, help_text="Show popup reminders"),
                ),
                (
                    "reminder_method_email",
                    models.BooleanField(default=True, help_text="Send email reminders"),
                ),
                (
                    "sync_only_assigned_tasks",
                    models.BooleanField(
                        default=True,
                        help_text="Only sync tasks assigned to the connected user",
                    ),
                ),
                (
                    "sync_high_priority_only",
                    models.BooleanField(
                        default=False, help_text="Only sync high priority tasks"
                    ),
                ),
                (
                    "auto_create_client_folders",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create Google Drive folders for new clients",
                    ),
                ),
                (
                    "drive_folder_structure",
                    models.CharField(
                        default="NexPro/{client_name}/{year}",
                        help_text="Folder structure template: {client_name}, {year}, {work_type}",
                        max_length=500,
                    ),
                ),
                (
                    "auto_upload_attachments",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-upload task attachments to Google Drive",
                    ),
                ),
                (
                    "auto_save_reports",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-save generated reports to Google Drive",
                    ),
                ),
                (
                    "send_notifications_via_gmail",
                    models.BooleanField(
                        default=False,
                        help_text="Send task notifications via connected Gmail",
                    ),
                ),
                (
                    "create_tasks_from_starred_emails",
                    models.BooleanField(
                        default=False,
                        help_text="Create NexPro tasks from starred Gmail messages",
                    ),
                ),
                (
                    "gmail_task_label",
                    models.CharField(
                        default="NexPro-Task",
                        help_text="Gmail label to watch for task creation",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "sync_work_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sync only these work types (empty = all)",
                        related_name="google_sync_settings",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sync Settings",
                "verbose_name_plural": "Google Sync Settings",
                "db_table": "google_sync_settings",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(
                        help_text="Google Calendar Event ID", max_length=255
                    ),
                ),
                (
                    "google_calendar_id",
                    models.CharField(help_text="Google Calendar ID", max_length=255),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "nexpro_updated_at",
                    models.DateTimeField(help_text="Last update time in NexPro"),
                ),
                (
                    "google_updated_at",
                    models.DateTimeField(
                        blank=True, help_text="Last update time in Google", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_mapping",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "google_calendar_mappings",
                "indexes": [
                    models.Index(
                        fields=["google_event_id", "google_calendar_id"],
                        name="google_cale_google__13a2b8_idx",
                    ),
                    models.Index(
                        fields=["user", "work_instance"],
                        name="google_cale_user_id_76b1ea_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoogleConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted Google OAuth access token",
                        null=True,
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted Google OAuth refresh token",
                        null=True,
                    ),
                ),
                (
                    "token_expiry",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                (
                    "google_email",
                    models.EmailField(
                        blank=True,
                        help_text="Connected Google account email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "google_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Google user ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("EXPIRED", "Token Expired"),
                            ("ERROR", "Error"),
                        ],
                        default="DISCONNECTED",
                        max_length=20,
                    ),
                ),
                (
                    "tasks_enabled",
                    models.BooleanField(
                        default=False, help_text="Google Tasks sync enabled"
                    ),
                ),
                (
                    "calendar_enabled",
                    models.BooleanField(
                        default=False, help_text="Google Calendar sync enabled"
                    ),
                ),
                (
                    "drive_enabled",
                    models.BooleanField(
                        default=False, help_text="Google Drive sync enabled"
                    ),
                ),
                (
                    "gmail_enabled",
                    models.BooleanField(
                        default=False, help_text="Gmail integration enabled"
                    ),
                ),
                (
                    "tasks_list_id",
                    models.CharField(
                        blank=True,
                        help_text="Default Google Tasks list ID for syncing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "calendar_id",
                    models.CharField(
                        blank=True,
                        help_text="Default Google Calendar ID for syncing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Root Google Drive folder ID for NexPro files",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the connection was established",
                        null=True,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync timestamp",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "google_connections",
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="google_conn_organiz_3bca75_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="google_conn_user_id_f23d25_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoogleDriveMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client Folder"),
                            ("WORK_TYPE", "Work Type Folder"),
                            ("YEAR", "Year Folder"),
                            ("TASK", "Task Folder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "google_folder_id",
                    models.CharField(
                        help_text="Google Drive Folder ID", max_length=255
                    ),
                ),
                (
                    "google_folder_name",
                    models.CharField(
                        help_text="Folder name in Google Drive", max_length=255
                    ),
                ),
                (
                    "parent_folder_id",
                    models.CharField(
                        blank=True,
                        help_text="Parent folder ID in Google Drive",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_drive_folders",
                        to="core.client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "shared_with_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_google_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_drive_folders",
                        to="core.workinstance",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_drive_folders",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "db_table": "google_drive_mappings",
                "indexes": [
                    models.Index(
                        fields=["organization", "folder_type"],
                        name="google_driv_organiz_86bfd2_idx",
                    ),
                    models.Index(
                        fields=["client"], name="google_driv_client__711535_idx"
                    ),
                    models.Index(
                        fields=["google_folder_id"],
                        name="google_driv_google__5b2d47_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoogleSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("TASK_TO_GOOGLE", "Task synced to Google Tasks"),
                            ("TASK_FROM_GOOGLE", "Task synced from Google Tasks"),
                            ("CALENDAR_TO_GOOGLE", "Event synced to Google Calendar"),
                            (
                                "CALENDAR_FROM_GOOGLE",
                                "Event synced from Google Calendar",
                            ),
                            ("DRIVE_UPLOAD", "File uploaded to Google Drive"),
                            ("DRIVE_FOLDER_CREATE", "Folder created in Google Drive"),
                            ("GMAIL_SEND", "Email sent via Gmail"),
                            ("GMAIL_TASK_CREATE", "Task created from Gmail"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "google_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Sync operation details", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="google_sync_logs",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "google_sync_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "sync_type", "-created_at"],
                        name="google_sync_organiz_94be97_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="google_sync_user_id_8abfae_idx"
                    ),
                    models.Index(
                        fields=["work_instance"], name="google_sync_work_in_2e4f51_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoogleTaskMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_task_id",
                    models.CharField(help_text="Google Task ID", max_length=255),
                ),
                (
                    "google_tasklist_id",
                    models.CharField(help_text="Google Task List ID", max_length=255),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "nexpro_updated_at",
                    models.DateTimeField(
                        help_text="Last update time in NexPro (for conflict detection)"
                    ),
                ),
                (
                    "google_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last update time in Google (for conflict detection)",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_task_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_task_mapping",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "google_task_mappings",
                "indexes": [
                    models.Index(
                        fields=["google_task_id", "google_tasklist_id"],
                        name="google_task_google__27c54a_idx",
                    ),
                    models.Index(
                        fields=["user", "work_instance"],
                        name="google_task_user_id_f18203_idx",
                    ),
                ],
            },
        ),
    ]
