# Generated by Django 5.0.1 on 2025-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_googlesyncsettings_googlecalendarmapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="google_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google OAuth Client ID from Google Cloud Console",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="google_client_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google OAuth Client Secret (stored encrypted)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="google_oauth_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Google OAuth for Google Sync Hub"
            ),
        ),
    ]
