# Generated by Django 5.0.1 on 2025-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_encrypt_platform_settings_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="google_calendar_daily_quota",
            field=models.PositiveIntegerField(
                default=1000000,
                help_text="Google Calendar API daily quota limit (default: 1,000,000)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="google_drive_daily_quota",
            field=models.PositiveIntegerField(
                default=1000000000,
                help_text="Google Drive API daily quota limit (default: 1,000,000,000)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="google_gmail_daily_quota",
            field=models.PositiveIntegerField(
                default=1000000, help_text="Gmail API daily quota units limit"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="google_tasks_daily_quota",
            field=models.PositiveIntegerField(
                default=50000,
                help_text="Google Tasks API daily quota limit (default: 50,000)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="quota_critical_threshold",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Percentage at which to critically alert about quota usage",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="quota_warning_threshold",
            field=models.PositiveIntegerField(
                default=70, help_text="Percentage at which to warn about quota usage"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_calendar_enabled",
            field=models.BooleanField(
                default=False, help_text="Google Calendar sync available"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_drive_enabled",
            field=models.BooleanField(
                default=False, help_text="Google Drive sync available"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_gmail_enabled",
            field=models.BooleanField(
                default=False, help_text="Gmail integration available"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether Google Sync is available for this plan",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_sync_frequency_minutes",
            field=models.IntegerField(
                choices=[
                    (0, "Disabled"),
                    (15, "Every 15 minutes"),
                    (30, "Every 30 minutes"),
                    (60, "Every hour"),
                    (120, "Every 2 hours"),
                    (360, "Every 6 hours"),
                    (720, "Every 12 hours"),
                    (1440, "Once daily"),
                    (-1, "Manual only"),
                ],
                default=-1,
                help_text="Minimum interval between automatic syncs (-1 = manual only, 0 = disabled)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="google_tasks_enabled",
            field=models.BooleanField(
                default=False, help_text="Google Tasks sync available"
            ),
        ),
        migrations.CreateModel(
            name="GoogleAPIQuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of usage tracking")),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("TASKS", "Google Tasks"),
                            ("CALENDAR", "Google Calendar"),
                            ("DRIVE", "Google Drive"),
                            ("GMAIL", "Gmail"),
                        ],
                        help_text="Which Google API",
                        max_length=20,
                    ),
                ),
                (
                    "queries_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of API queries made"
                    ),
                ),
                (
                    "quota_units_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Quota units consumed (for Gmail)"
                    ),
                ),
                (
                    "read_operations",
                    models.PositiveIntegerField(
                        default=0, help_text="Read/Get operations"
                    ),
                ),
                (
                    "write_operations",
                    models.PositiveIntegerField(
                        default=0, help_text="Create/Update operations"
                    ),
                ),
                (
                    "delete_operations",
                    models.PositiveIntegerField(
                        default=0, help_text="Delete operations"
                    ),
                ),
                (
                    "unique_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of unique users making requests"
                    ),
                ),
                (
                    "unique_organizations",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of unique organizations making requests",
                    ),
                ),
                (
                    "failed_requests",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed API requests"
                    ),
                ),
                (
                    "rate_limit_hits",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of rate limit errors encountered"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "google_api_quota_usage",
                "ordering": ["-date", "api_type"],
                "indexes": [
                    models.Index(fields=["date"], name="google_api__date_ad6ea0_idx"),
                    models.Index(
                        fields=["api_type"], name="google_api__api_typ_cf4888_idx"
                    ),
                ],
                "unique_together": {("date", "api_type")},
            },
        ),
    ]
