# Generated by Django 5.0.1 on 2025-12-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_add_google_quota_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="has_subtasks",
            field=models.BooleanField(
                default=False, help_text="Enable subtasks for this task category"
            ),
        ),
        migrations.CreateModel(
            name="SubTaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the subtask", max_length=255),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Is this subtask mandatory for task completion?",
                    ),
                ),
                (
                    "is_auto_driven",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-driven subtasks start automatically and send reminders until completed",
                    ),
                ),
                (
                    "due_days_before_parent",
                    models.IntegerField(
                        default=0,
                        help_text="Days before parent task due date (0 = same as parent, -5 = 5 days before)",
                    ),
                ),
                (
                    "enable_client_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic reminders to clients for this subtask",
                    ),
                ),
                (
                    "client_reminder_start_day",
                    models.IntegerField(
                        default=1,
                        help_text="Day of month/period to start sending client reminders",
                    ),
                ),
                (
                    "client_reminder_end_day",
                    models.IntegerField(
                        default=0,
                        help_text="Day to stop client reminders (0 = due date)",
                    ),
                ),
                (
                    "client_reminder_frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("ALTERNATE_DAYS", "Every Alternate Days"),
                            ("WEEKLY", "Weekly (Specific Days)"),
                            ("CUSTOM", "Custom Interval"),
                        ],
                        default="ALTERNATE_DAYS",
                        max_length=20,
                    ),
                ),
                ("client_reminder_interval_days", models.IntegerField(default=2)),
                (
                    "client_reminder_weekdays",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "enable_employee_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic reminders to assigned employees for this subtask",
                    ),
                ),
                (
                    "employee_notification_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email Only"),
                            ("IN_APP", "In-App Notification Only"),
                            ("BOTH", "Both Email & In-App"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                ("employee_reminder_start_day", models.IntegerField(default=1)),
                ("employee_reminder_end_day", models.IntegerField(default=0)),
                (
                    "employee_reminder_frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("ALTERNATE_DAYS", "Every Alternate Days"),
                            ("WEEKLY", "Weekly (Specific Days)"),
                            ("CUSTOM", "Custom Interval"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("employee_reminder_interval_days", models.IntegerField(default=1)),
                (
                    "employee_reminder_weekdays",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtask_categories",
                        to="core.worktype",
                    ),
                ),
            ],
            options={
                "db_table": "subtask_categories",
                "ordering": ["work_type", "order", "name"],
                "unique_together": {("work_type", "name", "organization")},
            },
        ),
    ]
