# Generated by Django 5.0.1 on 2025-12-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_add_subtask_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AWS Access Key ID for SES",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="aws_region",
            field=models.CharField(
                blank=True,
                default="us-east-1",
                help_text="AWS Region for SES (e.g., us-east-1, ap-south-1)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="aws_secret_access_key_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="AWS Secret Access Key (encrypted)"
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="email_daily_limit_per_org",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Maximum emails per organization per day (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="email_daily_limit_platform",
            field=models.PositiveIntegerField(
                default=10000,
                help_text="Maximum total emails platform-wide per day (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="email_provider",
            field=models.CharField(
                choices=[
                    ("SMTP", "SMTP (Gmail, Custom)"),
                    ("SENDGRID", "SendGrid"),
                    ("SES", "Amazon SES"),
                ],
                default="SMTP",
                help_text="Email service provider to use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="sendgrid_api_key_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="SendGrid API Key (encrypted)"
            ),
        ),
        migrations.AlterField(
            model_name="googledrivemapping",
            name="folder_type",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client Folder"),
                    ("WORK_TYPE", "Task Category Folder"),
                    ("YEAR", "Year Folder"),
                    ("TASK", "Task Folder"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="googlesyncsettings",
            name="sync_work_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sync only these task categories (empty = all)",
                related_name="google_sync_settings",
                to="core.worktype",
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="include_work_type_wise",
            field=models.BooleanField(
                default=True, help_text="Include task category-wise task breakdown"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="enable_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic reminders for this task category",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="sender_email",
            field=models.ForeignKey(
                blank=True,
                help_text="Email account to use for sending reminders for this task category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_types",
                to="core.organizationemail",
            ),
        ),
        migrations.CreateModel(
            name="EmailUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="The date for this usage record")),
                (
                    "email_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of emails sent"
                    ),
                ),
                (
                    "last_email_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of the last email sent"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_usage_logs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "email_usage_logs",
                "indexes": [
                    models.Index(fields=["date"], name="email_usage_date_1cb931_idx"),
                    models.Index(
                        fields=["organization", "date"],
                        name="email_usage_organiz_7267c6_idx",
                    ),
                ],
                "unique_together": {("organization", "date")},
            },
        ),
    ]
