# Generated by Django 5.0.1 on 2025-12-09 22:57

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_custom_smtp(apps, schema_editor):
    """
    Update existing email accounts that have custom SMTP configured
    to use the new smtp_source field.
    """
    OrganizationEmail = apps.get_model('core', 'OrganizationEmail')
    # Update accounts that have use_custom_smtp=True or have smtp_host configured
    OrganizationEmail.objects.filter(use_custom_smtp=True).update(smtp_source='CUSTOM')
    OrganizationEmail.objects.filter(smtp_host__isnull=False).exclude(smtp_host='').update(smtp_source='CUSTOM')


def reverse_migration(apps, schema_editor):
    """Reverse the data migration (no-op, we keep the use_custom_smtp field)."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_add_email_provider_and_usage_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationemail",
            name="smtp_inherit_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Inherit SMTP settings from this email account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="smtp_dependents",
                to="core.organizationemail",
            ),
        ),
        migrations.AddField(
            model_name="organizationemail",
            name="smtp_source",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Use Platform SMTP"),
                    ("CUSTOM", "Custom SMTP Settings"),
                    ("INHERIT", "Use Another Account's SMTP"),
                ],
                default="PLATFORM",
                help_text="Where to get SMTP settings from",
                max_length=20,
            ),
        ),
        # Data migration to update existing custom SMTP accounts
        migrations.RunPython(migrate_existing_custom_smtp, reverse_migration),
    ]
