# Generated by Django 5.0.1 on 2025-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_add_smtp_source_and_inherit"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportconfiguration",
            name="recipient_roles",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of roles (ADMIN, PARTNER, MANAGER, STAFF)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("SPECIFIC_USERS", "Specific Users"),
                    ("BY_ROLE", "All Users with Specific Roles"),
                ],
                default="SPECIFIC_USERS",
                help_text="How to determine report recipients",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="recipient_user_ids",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of user IDs within the organization",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="recipient_emails",
            field=models.TextField(
                blank=True,
                help_text="Deprecated: Use recipient_user_ids or recipient_roles instead",
                null=True,
            ),
        ),
    ]
