# Generated by Django 5.0.1 on 2025-12-17 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_add_recipient_type_to_report_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique tracking ID for this email (UUID)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SMTP Message-ID header value",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gmail API message ID (for Gmail-sent emails)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gmail_thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Gmail thread ID for conversation tracking",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(help_text="Sender email address", max_length=254),
                ),
                (
                    "to_email",
                    models.EmailField(
                        help_text="Primary recipient email address", max_length=254
                    ),
                ),
                (
                    "cc_emails",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="CC recipients (comma-separated)",
                    ),
                ),
                (
                    "bcc_emails",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="BCC recipients (comma-separated)",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject", max_length=500),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("REMINDER_CLIENT", "Client Reminder"),
                            ("REMINDER_EMPLOYEE", "Employee Reminder"),
                            ("NOTIFICATION", "Notification"),
                            ("OTP", "OTP/Verification"),
                            ("REPORT", "Report"),
                            ("TASK_ASSIGNMENT", "Task Assignment"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("WELCOME", "Welcome Email"),
                            ("CUSTOM", "Custom Email"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type/purpose of email",
                        max_length=30,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("SMTP", "SMTP"),
                            ("SENDGRID", "SendGrid"),
                            ("SES", "Amazon SES"),
                            ("GMAIL_API", "Gmail API"),
                        ],
                        default="SMTP",
                        help_text="Email provider used to send",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("BOUNCED", "Bounced"),
                            ("FAILED", "Failed"),
                            ("SPAM", "Marked as Spam"),
                        ],
                        default="PENDING",
                        help_text="Email delivery status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was delivered (if known)",
                        null=True,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was opened (if tracked)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if sending failed",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (headers, attachments info, etc.)",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related client (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="core.client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "reminder_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related reminder instance (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="core.reminderinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the email (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related work instance (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="core.workinstance",
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tracking_id"], name="email_logs_trackin_beac4b_idx"
                    ),
                    models.Index(
                        fields=["message_id"], name="email_logs_message_367807_idx"
                    ),
                    models.Index(
                        fields=["gmail_message_id"],
                        name="email_logs_gmail_m_e28034_idx",
                    ),
                    models.Index(
                        fields=["to_email"], name="email_logs_to_emai_9c46ac_idx"
                    ),
                    models.Index(
                        fields=["email_type"], name="email_logs_email_t_fe5930_idx"
                    ),
                    models.Index(
                        fields=["status"], name="email_logs_status_e3be55_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="email_logs_created_76afc3_idx"
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="email_logs_organiz_cc3ec3_idx",
                    ),
                    models.Index(
                        fields=["work_instance"], name="email_logs_work_in_7db8d2_idx"
                    ),
                ],
            },
        ),
    ]
